# Generated by Django 4.1.3 on 2022-12-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(blank=True, default='默认相册', max_length=20, null=True, verbose_name='相册标题')),
                ('album_intro', models.TextField(blank=True, verbose_name='相册引言')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='p', max_length=1, null=True, verbose_name='Status (*)')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(blank=True, max_length=20, verbose_name='照片标题')),
                ('photo_intro', models.TextField(blank=True, verbose_name='照片引言')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('photo_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.album', verbose_name='照片链接')),
            ],
        ),
    ]
