# Generated by Django 4.1.3 on 2022-12-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(blank=True, max_length=20, verbose_name='照片标题')),
                ('photo_intro', models.TextField(blank=True, verbose_name='照片引言')),
                ('photo_url', models.CharField(blank=True, max_length=512, verbose_name='图片链接')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('photo_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.album', verbose_name='归属相册')),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
