# Generated by Django 4.1.3 on 2022-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_topic', models.CharField(blank=True, choices=[('p', 'Python'), ('g', 'GO'), ('n', 'News')], default='P', max_length=1, null=True, verbose_name='话题')),
                ('article_title', models.CharField(max_length=50, verbose_name='标题')),
                ('article_author', models.CharField(default='茉茉', max_length=20, verbose_name='作者')),
                ('article_body', models.TextField(blank=True, verbose_name='内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='P', max_length=1, null=True, verbose_name='Status (*)')),
            ],
        ),
    ]
